#カメラの基本設定
camera:
  #左カメラのID
  left_index: 0
  #右カメラのID
  right_index: 2
  #物体検知に使用するメインカメラ（left / right)
  detection_source: "left"
  #画面の解像度
  width:  640
  height: 480

#測定用の数値
measure:
  #カメラの中心間の距離（㎜）
  baseline_mm: 75.0
  #カメラのレンズ性能
  focal_length_px: 500.0
  #背景と物体との区別精度
  diff_threhold: 30

#キャリブレーション用チェッカーマーク数値
checkerboard:
  num_squares_x: 10
  num_squares_y: 7
  # 1マスのサイズ (mm)
  square_size_mm: 15.0



